# Generated by Django 5.1 on 2024-08-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefone',
        ),
    ]
