# Generated by Django 5.1 on 2024-09-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_remove_paciente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='senha',
            field=models.CharField(max_length=64),
        ),
    ]
