# Generated by Django 5.1 on 2024-09-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0004_alter_paciente_senha'),
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profissional.especialidade')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profissional.profissional')),
            ],
            options={
                'verbose_name': 'Agenda',
            },
        ),
    ]
