# Generated by Django 5.1 on 2024-09-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(choices=[('Acupuntura', 'Acupuntura'), ('F.Cardiovascular', 'F.Cardiovascular'), ('F.Aquática', 'F.Aquática'), ('F.Esportiva', 'F.Esportiva')], default='Acuputura', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('area_especializacao', models.ManyToManyField(to='profissional.especialidade')),
            ],
        ),
    ]
