# Generated by Django 5.1 on 2024-08-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(choices=[('F.Aquática', 'F.Aquática'), ('F.Esportiva', 'F.Esportiva'), ('F.Cardiovascular', 'F.Cardiovascular'), ('Acupuntura', 'Acupuntura')], default='Acunputura', max_length=30),
        ),
    ]
