# Generated by Django 5.1 on 2024-08-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0002_alter_profissional_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(choices=[('F.Aquática', 'F.Aquática'), ('Acupuntura', 'Acupuntura'), ('F.Cardiovascular', 'F.Cardiovascular'), ('F.Esportiva', 'F.Esportiva')], default='Acunputura', max_length=100),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
