# Generated by Django 5.1 on 2024-09-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0003_alter_especialidade_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='especialidade',
            field=models.CharField(choices=[('Acupuntura', 'Acupuntura'), ('F.Cardiovascular', 'F.Cardiovascular'), ('F.Aquática', 'F.Aquática'), ('F.Esportiva', 'F.Esportiva')], default='Acuputura', max_length=100),
        ),
    ]
