# Generated by Django 5.1 on 2024-08-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0004_alter_profissional_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(choices=[('F.Aquática', 'F.Aquática'), ('F.Esportiva', 'F.Esportiva'), ('Acupuntura', 'Acupuntura'), ('F.Cardiovascular', 'F.Cardiovascular')], default='Acunputura', max_length=100),
        ),
    ]
