# Generated by Django 5.1 on 2024-09-01 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0005_alter_especialidade_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='especialidade',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='area_especializacao',
        ),
        migrations.AddField(
            model_name='profissional',
            name='area_especializacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='profissional.especialidade'),
            preserve_default=False,
        ),
    ]
