# Generated by Django 5.1 on 2024-09-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0005_alter_profissional_especialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(choices=[('F.Cardiovascular', 'F.Cardiovascular'), ('F.Aquática', 'F.Aquática'), ('Acupuntura', 'Acupuntura'), ('F.Esportiva', 'F.Esportiva')], default='Acunputura', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='profissional',
            name='area_especializacao',
            field=models.ManyToManyField(to='profissional.especialidade'),
        ),
    ]
